// SPDX-FileCopyrightText: 2026 AurielSolaris
// SPDX-License-Identifier: GPL-3.0-or-later

package app.auriel.choir.playback

import androidx.media3.common.C
import androidx.media3.common.util.UnstableApi
import androidx.media3.extractor.Extractor
import androidx.media3.extractor.PositionHolder
import org.junit.jupiter.api.Assertions.assertArrayEquals
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

/**
 * Monkey's Audio files built by hand, so a fixture cannot drift from the format
 * it claims to represent.
 *
 * The descriptor, the header and the seek table are written here from the
 * layout each version fixed, rather than taken from a file an encoder produced:
 * a fixture generated by the same misunderstanding as the parser would agree
 * with it perfectly and prove nothing.
 *
 * Frame sizes throughout are deliberately not multiples of four. That is the
 * whole difficulty of the format — the decoder reads on a four-byte grid that
 * the frames themselves do not sit on — and a fixture with tidy sizes would
 * never exercise the alignment arithmetic at all.
 */
@UnstableApi
class ApeExtractorTest {

    // --- What the file says it is --------------------------------------------

    @Test
    fun `publishes the format the header describes`() {
        val file = apeFile(frames = threeFrames())
        val output = extractAll(ApeExtractor(), FakeExtractorInput(file.bytes))

        val format = requireNotNull(output.track.format)
        assertEquals(ChoirMimeTypes.AUDIO_APE, format.sampleMimeType)
        assertEquals(44_100, format.sampleRate)
        assertEquals(2, format.channelCount)
    }

    @Test
    fun `hands the decoder the six bytes it opens with`() {
        val file = apeFile(
            fileVersion = 3990,
            compressionLevel = 2000,
            formatFlags = 0,
            frames = threeFrames(),
        )
        val output = extractAll(ApeExtractor(), FakeExtractorInput(file.bytes))

        val extraData = requireNotNull(output.track.format).initializationData[0]
        assertArrayEquals(
            byteArrayOf(
                0x96.toByte(), 0x0F, // 3990
                0xD0.toByte(), 0x07, // 2000
                0x00, 0x00, // no flags
            ),
            extraData,
        )
    }

    @Test
    fun `carries the bit depth the decoder refuses to open without`() {
        val file = apeFile(bitsPerSample = 24, frames = threeFrames())
        val output = extractAll(ApeExtractor(), FakeExtractorInput(file.bytes))

        val context = requireNotNull(output.track.format).initializationData[1]
        val values = requireNotNull(ChoirCodecContext.decode(context))
        assertEquals(24, values.bitsPerCodedSample)
    }

    @Test
    fun `duration counts every frame but the last in full`() {
        val file = apeFile(
            blocksPerFrame = 9_216,
            finalFrameBlocks = 4_608,
            sampleRate = 44_100,
            frames = threeFrames(),
        )
        val output = extractAll(ApeExtractor(), FakeExtractorInput(file.bytes))

        // Two whole frames and one half-length one.
        val blocks = 2L * 9_216 + 4_608
        assertEquals(
            blocks * C.MICROS_PER_SECOND / 44_100,
            requireNotNull(output.seekMap).durationUs,
        )
    }

    // --- Frames --------------------------------------------------------------

    @Test
    fun `every frame is handed over with its block count and skip`() {
        val file = apeFile(blocksPerFrame = 9_216, finalFrameBlocks = 4_608, frames = threeFrames())
        val output = extractAll(ApeExtractor(), FakeExtractorInput(file.bytes))

        assertEquals(3, output.track.samples.size)

        // The first frame defines the grid, so it is never skipped into. The
        // two after it start 10 and 23 bytes along, which is 2 and 3 past a
        // word boundary.
        assertEquals(listOf(0L, 2L, 3L), output.track.samples.map { it.skip })
        assertEquals(listOf(9_216L, 9_216L, 4_608L), output.track.samples.map { it.blocks })
    }

    @Test
    fun `a frame is handed over from its word boundary, not its first byte`() {
        val file = apeFile(frames = threeFrames())
        val output = extractAll(ApeExtractor(), FakeExtractorInput(file.bytes))

        // The second frame starts at 98 and is handed over from 96, so the two
        // bytes it is told to skip are the tail of the frame before it.
        val second = output.track.samples[1]
        val start = file.framePositions[1] - second.skip.toInt()
        assertArrayEquals(
            file.bytes.copyOfRange(start, start + second.payload.size),
            second.payload,
        )
    }

    @Test
    fun `timestamps advance one frame of blocks at a time`() {
        val file = apeFile(blocksPerFrame = 9_216, sampleRate = 44_100, frames = threeFrames())
        val output = extractAll(ApeExtractor(), FakeExtractorInput(file.bytes))

        // Computed from the block a frame starts at rather than by multiplying
        // one frame's length, because the two disagree by a microsecond once
        // rounding accumulates — and it is the block that is the truth.
        val timeOfFrame = { index: Long -> index * 9_216L * C.MICROS_PER_SECOND / 44_100 }
        assertEquals(
            listOf(timeOfFrame(0), timeOfFrame(1), timeOfFrame(2)),
            output.track.samples.map { it.timeUs },
        )
    }

    @Test
    fun `every frame is a key frame, because every frame decodes alone`() {
        val file = apeFile(frames = threeFrames())
        val output = extractAll(ApeExtractor(), FakeExtractorInput(file.bytes))

        assertTrue(output.track.samples.all { it.isKeyFrame })
    }

    @Test
    fun `a file that stops early gives up the frames it has`() {
        val file = apeFile(frames = threeFrames())
        val truncated = file.bytes.copyOfRange(0, file.framePositions[2] + 2)

        val output = extractAll(ApeExtractor(), FakeExtractorInput(truncated))

        // The last frame is short rather than absent: what arrived is real
        // audio, and the frame table said where it began.
        assertEquals(3, output.track.samples.size)
    }

    // --- Seeking -------------------------------------------------------------

    @Test
    fun `seeking lands on a frame rather than near one`() {
        val file = apeFile(blocksPerFrame = 9_216, sampleRate = 44_100, frames = threeFrames())
        val output = extractAll(ApeExtractor(), FakeExtractorInput(file.bytes))
        val seekMap = requireNotNull(output.seekMap)

        val perFrame = 9_216L * C.MICROS_PER_SECOND / 44_100
        // A time in the middle of the second frame resolves to the start of it.
        val point = seekMap.getSeekPoints(perFrame + perFrame / 2).first
        assertEquals(perFrame, point.timeUs)
        assertEquals((file.framePositions[1] - 2).toLong(), point.position)
    }

    @Test
    fun `reading resumes at the frame a seek asked for`() {
        val file = apeFile(blocksPerFrame = 9_216, sampleRate = 44_100, frames = threeFrames())
        val input = FakeExtractorInput(file.bytes)
        val extractor = ApeExtractor()

        // Read the header, then jump as the player would.
        val output = FakeExtractorOutput()
        extractor.init(output)
        extractor.read(input, PositionHolder())

        val seekMap = requireNotNull(output.seekMap)
        // Somewhere inside the third frame, rather than exactly at its start:
        // asking for the boundary itself lands a microsecond short of it once
        // the conversion has been rounded twice, which is frame two's answer.
        val insideLastFrame = 2 * 9_216L * C.MICROS_PER_SECOND / 44_100 + 1_000
        val point = seekMap.getSeekPoints(insideLastFrame).first
        input.seekTo(point.position)
        extractor.seek(point.position, point.timeUs)

        val seekPosition = PositionHolder()
        while (extractor.read(input, seekPosition) != Extractor.RESULT_END_OF_INPUT) Unit

        assertEquals(1, output.track.samples.size)
        assertEquals(point.timeUs, output.track.samples.first().timeUs)
    }

    // --- The older layout ----------------------------------------------------

    @Test
    fun `reads a file from before the descriptor existed`() {
        val file = apeFile(fileVersion = 3960, frames = threeFrames())
        val output = extractAll(ApeExtractor(), FakeExtractorInput(file.bytes))

        val format = requireNotNull(output.track.format)
        assertEquals(44_100, format.sampleRate)
        assertEquals(2, format.channelCount)
        assertEquals(3, output.track.samples.size)
    }

    @Test
    fun `the old layout takes its bit depth from a format flag`() {
        val file = apeFile(fileVersion = 3960, formatFlags = MAC_FLAG_24_BIT, frames = threeFrames())
        val output = extractAll(ApeExtractor(), FakeExtractorInput(file.bytes))

        val context = requireNotNull(output.track.format).initializationData[1]
        assertEquals(24, requireNotNull(ChoirCodecContext.decode(context)).bitsPerCodedSample)
    }

    @Test
    fun `the old layout steps over a peak level where the flags promise one`() {
        val file = apeFile(
            fileVersion = 3960,
            formatFlags = MAC_FLAG_HAS_PEAK_LEVEL,
            frames = threeFrames(),
        )
        val output = extractAll(ApeExtractor(), FakeExtractorInput(file.bytes))

        // Four bytes shifted everything; had they been read as header the
        // sample rate would be nonsense and no frame would land.
        assertEquals(44_100, requireNotNull(output.track.format).sampleRate)
        assertEquals(3, output.track.samples.size)
    }

    @Test
    fun `frame size is inferred from the version where the file omits it`() {
        assertEquals(9_216, legacyBlocksPerFrame(fileVersion = 3800, compressionLevel = 2000))
        assertEquals(73_728, legacyBlocksPerFrame(fileVersion = 3800, compressionLevel = 4000))
        assertEquals(73_728, legacyBlocksPerFrame(fileVersion = 3900, compressionLevel = 2000))
        assertEquals(73_728 * 4, legacyBlocksPerFrame(fileVersion = 3950, compressionLevel = 1000))
    }

    // --- Recognising a file --------------------------------------------------

    @Test
    fun `sniffs a file that begins with the magic`() {
        val file = apeFile(frames = threeFrames())
        assertTrue(ApeExtractor().sniff(FakeExtractorInput(file.bytes)))
    }

    @Test
    fun `sniffs past an ID3v2 tag no APE file should be carrying`() {
        val file = apeFile(id3Bytes = 64, frames = threeFrames())
        assertTrue(ApeExtractor().sniff(FakeExtractorInput(file.bytes)))
    }

    @Test
    fun `reads a file behind an ID3v2 tag`() {
        val file = apeFile(id3Bytes = 64, frames = threeFrames())
        val output = extractAll(ApeExtractor(), FakeExtractorInput(file.bytes))

        assertEquals(44_100, requireNotNull(output.track.format).sampleRate)
        assertEquals(3, output.track.samples.size)
    }

    @Test
    fun `declines a file whose magic is something else`() {
        val notApe = ByteArray(64).also { "RIFF".forEachIndexed { i, c -> it[i] = c.code.toByte() } }
        assertFalse(ApeExtractor().sniff(FakeExtractorInput(notApe)))
    }

    @Test
    fun `declines a version from a future it cannot read`() {
        val file = apeFile(fileVersion = 4200, frames = threeFrames())
        assertFalse(ApeExtractor().sniff(FakeExtractorInput(file.bytes)))
    }

    @Test
    fun `declines a file with no seek table, having no way to find a frame`() {
        val file = apeFile(frames = threeFrames(), seekTable = false)
        val output = extractAll(ApeExtractor(), FakeExtractorInput(file.bytes))

        assertNull(output.track.format)
        assertTrue(output.track.samples.isEmpty())
    }

    @Test
    fun `truncates a seek table whose offsets stop ascending`() {
        val file = apeFile(frames = threeFrames(), scrambleSeekTable = true)
        val output = extractAll(ApeExtractor(), FakeExtractorInput(file.bytes))

        // The first frame is locatable; nothing after the fold is.
        assertEquals(1, output.track.samples.size)
    }
}

// --- Fixtures ----------------------------------------------------------------

/** A file and the offsets of the frames inside it, for a test to check against. */
private class ApeFile(val bytes: ByteArray, val framePositions: IntArray)

/**
 * Three frames whose sizes are all odd of a word, which is what puts the two
 * later ones 2 and 3 bytes past the grid the decoder reads on.
 */
private fun threeFrames(): List<ByteArray> = listOf(
    ByteArray(10) { (it + 1).toByte() },
    ByteArray(13) { (it + 100).toByte() },
    ByteArray(7) { (it + 200).toByte() },
)

private fun apeFile(
    fileVersion: Int = 3990,
    compressionLevel: Int = 2000,
    formatFlags: Int = 0,
    blocksPerFrame: Int = 9_216,
    finalFrameBlocks: Int = 4_608,
    bitsPerSample: Int = 16,
    channels: Int = 2,
    sampleRate: Int = 44_100,
    frames: List<ByteArray>,
    id3Bytes: Int = 0,
    seekTable: Boolean = true,
    scrambleSeekTable: Boolean = false,
): ApeFile {
    val modern = fileVersion >= APE_DESCRIPTOR_VERSION
    val seekTableBytes = if (seekTable) frames.size * 4 else 0

    val headerBytes = if (modern) {
        APE_DESCRIPTOR_BYTES + APE_HEADER_BYTES
    } else {
        APE_LEGACY_HEADER_BYTES +
            (if (formatFlags and MAC_FLAG_HAS_PEAK_LEVEL != 0) 4 else 0) +
            (if (formatFlags and MAC_FLAG_HAS_SEEK_ELEMENTS != 0) 4 else 0)
    }

    val frameDataBytes = frames.sumOf { it.size }
    val firstFrame = id3Bytes + headerBytes + seekTableBytes
    val total = firstFrame + frameDataBytes

    val bytes = ByteArray(total)
    if (id3Bytes > 0) writeId3v2(bytes, id3Bytes)

    var at = id3Bytes
    "MAC ".forEachIndexed { index, character -> bytes[at + index] = character.code.toByte() }
    at += 4
    bytes.writeU16(at, fileVersion)
    at += 2

    if (modern) {
        bytes.writeU16(at, 0) // padding
        bytes.writeU32(at + 2, APE_DESCRIPTOR_BYTES.toLong())
        bytes.writeU32(at + 6, APE_HEADER_BYTES.toLong())
        bytes.writeU32(at + 10, seekTableBytes.toLong())
        bytes.writeU32(at + 14, 0) // no stored WAVE header
        bytes.writeU32(at + 18, frameDataBytes.toLong())
        bytes.writeU32(at + 22, 0) // frame data, high word
        bytes.writeU32(at + 26, 0) // nothing trailing
        at += APE_DESCRIPTOR_BYTES - 6

        bytes.writeU16(at, compressionLevel)
        bytes.writeU16(at + 2, formatFlags)
        bytes.writeU32(at + 4, blocksPerFrame.toLong())
        bytes.writeU32(at + 8, finalFrameBlocks.toLong())
        bytes.writeU32(at + 12, frames.size.toLong())
        bytes.writeU16(at + 16, bitsPerSample)
        bytes.writeU16(at + 18, channels)
        bytes.writeU32(at + 20, sampleRate.toLong())
        at += APE_HEADER_BYTES
    } else {
        bytes.writeU16(at, compressionLevel)
        bytes.writeU16(at + 2, formatFlags)
        bytes.writeU16(at + 4, channels)
        bytes.writeU32(at + 6, sampleRate.toLong())
        bytes.writeU32(at + 10, 0) // no stored WAVE header
        bytes.writeU32(at + 14, 0) // nothing trailing
        bytes.writeU32(at + 18, frames.size.toLong())
        bytes.writeU32(at + 22, finalFrameBlocks.toLong())
        at += APE_LEGACY_HEADER_BYTES - 6

        if (formatFlags and MAC_FLAG_HAS_PEAK_LEVEL != 0) {
            bytes.writeU32(at, 0x7FFF)
            at += 4
        }
        if (formatFlags and MAC_FLAG_HAS_SEEK_ELEMENTS != 0) {
            bytes.writeU32(at, frames.size.toLong())
            at += 4
        }
    }

    // The seek table states offsets from the start of the APE data, which is
    // why a tag written in front of it later does not invalidate the file.
    val positions = IntArray(frames.size)
    var framePosition = firstFrame
    for (index in frames.indices) {
        positions[index] = framePosition
        framePosition += frames[index].size
    }

    if (seekTable) {
        for (index in frames.indices) {
            val offset = (positions[index] - id3Bytes).toLong()
            val stated = if (scrambleSeekTable && index > 0) 0L else offset
            bytes.writeU32(at + index * 4, stated)
        }
        at += seekTableBytes
    }

    for (index in frames.indices) frames[index].copyInto(bytes, positions[index])
    return ApeFile(bytes, positions)
}

/** A tag of the stated total length, with a synchsafe size to match. */
private fun writeId3v2(bytes: ByteArray, totalBytes: Int) {
    bytes[0] = 'I'.code.toByte()
    bytes[1] = 'D'.code.toByte()
    bytes[2] = '3'.code.toByte()
    bytes[3] = 4
    bytes[4] = 0
    bytes[5] = 0

    var size = totalBytes - 10
    for (index in 9 downTo 6) {
        bytes[index] = (size and 0x7F).toByte()
        size = size shr 7
    }
}

// --- Reading back what the extractor wrote -----------------------------------

/** The block count the prefix states. */
private val WrittenSample.blocks: Long
    get() = bytes.u32le(0)

/** The skip the prefix states. */
private val WrittenSample.skip: Long
    get() = bytes.u32le(4)

/** The frame itself, behind the prefix Choir added for the decoder. */
private val WrittenSample.payload: ByteArray
    get() = bytes.copyOfRange(APE_PACKET_PREFIX_BYTES, bytes.size)

private fun ByteArray.writeU16(offset: Int, value: Int) {
    this[offset] = (value and 0xFF).toByte()
    this[offset + 1] = ((value shr 8) and 0xFF).toByte()
}

private fun ByteArray.writeU32(offset: Int, value: Long) {
    for (index in 0 until 4) {
        this[offset + index] = ((value shr (8 * index)) and 0xFF).toByte()
    }
}
