// SPDX-FileCopyrightText: 2026 AurielSolaris
// SPDX-License-Identifier: GPL-3.0-or-later

package app.auriel.choir.playback

import androidx.media3.common.C
import androidx.media3.common.util.UnstableApi
import androidx.media3.extractor.Extractor
import androidx.media3.extractor.PositionHolder
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

/**
 * WavPack blocks built by hand, so a fixture cannot drift from the format it
 * claims to represent.
 *
 * Every field here was written from the WavPack 5 block-header layout rather
 * than from a file produced by an encoder: a fixture generated by the same
 * misunderstanding as the parser would agree with it perfectly.
 */
private const val RATE_44100 = 9
private const val RATE_FROM_SUB_BLOCK = 15

private fun block(
    blockIndex: Long = 0L,
    blockSamples: Int = 22_050,
    totalSamples: Long = 44_100L,
    sampleRateIndex: Int = RATE_44100,
    mono: Boolean = false,
    initialBlock: Boolean = true,
    finalBlock: Boolean = true,
    version: Int = 0x0410,
    body: ByteArray = ByteArray(16) { it.toByte() },
): ByteArray {
    val bytes = ByteArray(WV_HEADER_BYTES + body.size)

    "wvpk".forEachIndexed { index, character -> bytes[index] = character.code.toByte() }
    // ckSize counts everything after itself.
    bytes.putU32le(WV_SIZE_OFFSET, (bytes.size - 8).toLong())
    bytes.putU16le(WV_VERSION_OFFSET, version)
    bytes[WV_BLOCK_INDEX_HIGH_OFFSET] = (blockIndex ushr 32).toByte()
    bytes[WV_TOTAL_SAMPLES_HIGH_OFFSET] =
        if (totalSamples < 0) 0 else (totalSamples ushr 32).toByte()
    bytes.putU32le(
        WV_TOTAL_SAMPLES_OFFSET,
        if (totalSamples < 0) 0xFFFF_FFFFL else totalSamples and 0xFFFF_FFFFL,
    )
    bytes.putU32le(WV_BLOCK_INDEX_OFFSET, blockIndex and 0xFFFF_FFFFL)
    bytes.putU32le(WV_SAMPLES_OFFSET, blockSamples.toLong())

    var flags = sampleRateIndex.toLong() shl 23
    if (mono) flags = flags or WV_FLAG_MONO
    if (initialBlock) flags = flags or 0x0000_0800L
    if (finalBlock) flags = flags or WV_FLAG_FINAL_BLOCK
    bytes.putU32le(WV_FLAGS_OFFSET, flags)

    body.copyInto(bytes, WV_HEADER_BYTES)
    return bytes
}

/** A metadata sub-block: id, a length in 16-bit words, then the data. */
private fun subBlock(function: Int, data: ByteArray): ByteArray {
    val odd = data.size % 2 == 1
    val words = (data.size + 1) / 2
    val id = function or if (odd) 0x40 else 0x00

    val bytes = ByteArray(2 + words * 2)
    bytes[0] = id.toByte()
    bytes[1] = words.toByte()
    data.copyInto(bytes, 2)
    return bytes
}

private fun ByteArray.putU16le(offset: Int, value: Int) {
    this[offset] = (value and 0xFF).toByte()
    this[offset + 1] = ((value shr 8) and 0xFF).toByte()
}

private fun ByteArray.putU32le(offset: Int, value: Long) {
    for (index in 0 until 4) {
        this[offset + index] = ((value shr (8 * index)) and 0xFF).toByte()
    }
}

private fun id3v2(payloadBytes: Int): ByteArray {
    val tag = ByteArray(10 + payloadBytes)
    tag[0] = 'I'.code.toByte()
    tag[1] = 'D'.code.toByte()
    tag[2] = '3'.code.toByte()
    tag[3] = 3
    // Synchsafe: seven bits per byte.
    tag[6] = ((payloadBytes shr 21) and 0x7F).toByte()
    tag[7] = ((payloadBytes shr 14) and 0x7F).toByte()
    tag[8] = ((payloadBytes shr 7) and 0x7F).toByte()
    tag[9] = (payloadBytes and 0x7F).toByte()
    return tag
}

@UnstableApi
class WavPackSniffTest {

    @Test
    fun `a WavPack file is recognised`() {
        assertTrue(WavPackExtractor().sniff(FakeExtractorInput(block())))
    }

    @Test
    fun `an ID3v2 tag in front of the audio is stepped over`() {
        val file = id3v2(payloadBytes = 64) + block()

        assertTrue(WavPackExtractor().sniff(FakeExtractorInput(file)))
    }

    @Test
    fun `the magic alone is not enough`() {
        // Right magic, impossible version: this is what a false positive inside
        // compressed audio looks like.
        val notAWavPack = block(version = 0x0100)

        assertFalse(WavPackExtractor().sniff(FakeExtractorInput(notAWavPack)))
    }

    @Test
    fun `another format is declined`() {
        val mp3 = ByteArray(64).also { it[0] = 0xFF.toByte(); it[1] = 0xFB.toByte() }

        assertFalse(WavPackExtractor().sniff(FakeExtractorInput(mp3)))
    }

    @Test
    fun `a file too short to hold a header is declined`() {
        assertFalse(WavPackExtractor().sniff(FakeExtractorInput(ByteArray(8))))
    }
}

@UnstableApi
class WavPackFormatTest {

    @Test
    fun `the header names the sample rate and channel count`() {
        val output = extractAll(WavPackExtractor(), FakeExtractorInput(block()))

        val format = requireNotNull(output.track.format)
        assertEquals(ChoirMimeTypes.AUDIO_WAVPACK, format.sampleMimeType)
        assertEquals(44_100, format.sampleRate)
        assertEquals(2, format.channelCount)
    }

    @Test
    fun `the mono flag is the only statement of a single channel`() {
        val output = extractAll(WavPackExtractor(), FakeExtractorInput(block(mono = true)))

        assertEquals(1, output.track.format?.channelCount)
    }

    @Test
    fun `duration comes from the total sample count`() {
        val file = block(totalSamples = 88_200L)

        val seekMap = requireNotNull(extractAll(WavPackExtractor(), FakeExtractorInput(file)).seekMap)
        assertEquals(2_000_000L, seekMap.durationUs)
    }

    @Test
    fun `a stream that will not say how long it is has no duration and no seeking`() {
        val file = block(totalSamples = -1L)

        val seekMap = requireNotNull(extractAll(WavPackExtractor(), FakeExtractorInput(file)).seekMap)
        assertEquals(C.TIME_UNSET, seekMap.durationUs)
        assertFalse(seekMap.isSeekable)
    }

    @Test
    fun `a sample rate outside the table is read from the sub-block that carries it`() {
        // Rate index 15 means "see the metadata". 352.8 kHz is a real rate —
        // eight times CD — and one the fifteen-entry table has no room for.
        val rate = byteArrayOf(0x20, 0x62, 0x05) // 0x056220 = 352800
        val file = block(
            sampleRateIndex = RATE_FROM_SUB_BLOCK,
            body = subBlock(function = 0x07, data = rate),
        )

        val output = extractAll(WavPackExtractor(), FakeExtractorInput(file))
        assertEquals(352_800, output.track.format?.sampleRate)
    }

    @Test
    fun `more than two channels are counted from the channel-info sub-block`() {
        val file = block(
            finalBlock = false,
            body = subBlock(function = 0x0D, data = byteArrayOf(6)),
        ) + block(blockIndex = 0L, initialBlock = false)

        val output = extractAll(WavPackExtractor(), FakeExtractorInput(file))
        assertEquals(6, output.track.format?.channelCount)
    }

    @Test
    fun `the seek map turns a time into a position and back into the same time`() {
        val file = block(totalSamples = 44_100L * 100)

        val seekMap = requireNotNull(extractAll(WavPackExtractor(), FakeExtractorInput(file)).seekMap)
        assertTrue(seekMap.isSeekable)

        val points = seekMap.getSeekPoints(seekMap.durationUs / 2)
        assertEquals(seekMap.durationUs / 2, points.first.timeUs)
        assertTrue(points.first.position > 0L)
    }
}

@UnstableApi
class WavPackSampleTest {

    @Test
    fun `each block becomes one sample, timed from the sample it starts at`() {
        val file = block(blockIndex = 0L) + block(blockIndex = 22_050L)

        val samples = extractAll(WavPackExtractor(), FakeExtractorInput(file)).track.samples

        assertEquals(2, samples.size)
        assertEquals(0L, samples[0].timeUs)
        assertEquals(500_000L, samples[1].timeUs)
    }

    @Test
    fun `the block header is handed to the decoder along with the block`() {
        val file = block()

        val sample = extractAll(WavPackExtractor(), FakeExtractorInput(file)).track.samples.single()

        assertEquals(file.size, sample.bytes.size)
        assertEquals("wvpk", String(sample.bytes, 0, 4, Charsets.US_ASCII))
    }

    @Test
    fun `every block is a key frame, because every block decodes on its own`() {
        val file = block(blockIndex = 0L) + block(blockIndex = 22_050L)

        val samples = extractAll(WavPackExtractor(), FakeExtractorInput(file)).track.samples
        assertTrue(samples.all(WrittenSample::isKeyFrame))
    }

    @Test
    fun `a block carrying only metadata is not offered to the decoder`() {
        val file = block(blockSamples = 0) + block(blockIndex = 0L)

        val samples = extractAll(WavPackExtractor(), FakeExtractorInput(file)).track.samples
        assertEquals(1, samples.size)
    }

    @Test
    fun `a multichannel frame is joined into one sample`() {
        val file = block(blockIndex = 0L, finalBlock = false) +
            block(blockIndex = 0L, initialBlock = false)

        val samples = extractAll(WavPackExtractor(), FakeExtractorInput(file)).track.samples

        assertEquals(1, samples.size)
        assertEquals(file.size, samples.single().bytes.size)
        assertEquals(0L, samples.single().timeUs)
    }

    @Test
    fun `a truncated final block ends the stream instead of emitting half a frame`() {
        val whole = block(blockIndex = 0L, finalBlock = false) +
            block(blockIndex = 0L, initialBlock = false)
        val truncated = whole.copyOfRange(0, whole.size - 8)

        val samples = extractAll(WavPackExtractor(), FakeExtractorInput(truncated)).track.samples
        assertTrue(samples.isEmpty())
    }

    @Test
    fun `junk between blocks is skipped rather than ending the track`() {
        // An APEv2 tag, an ID3v1 trailer, or a badly concatenated file.
        val junk = ByteArray(40) { 0x7F }
        val file = block(blockIndex = 0L) + junk + block(blockIndex = 22_050L)

        val samples = extractAll(WavPackExtractor(), FakeExtractorInput(file)).track.samples

        assertEquals(2, samples.size)
        assertEquals(500_000L, samples[1].timeUs)
    }

    @Test
    fun `a seek into the middle of a block resynchronises to the next one`() {
        val first = block(blockIndex = 0L)
        val file = first + block(blockIndex = 22_050L)
        val input = FakeExtractorInput(file)
        val extractor = WavPackExtractor()
        val output = FakeExtractorOutput()

        extractor.init(output)
        // The first read publishes the format and consumes nothing.
        extractor.read(input, PositionHolder())

        // Land four bytes short of the second block, which is what a position
        // derived from the average bitrate does.
        extractor.seek(first.size - 4L, 400_000L)
        input.seekTo(first.size - 4L)
        while (extractor.read(input, PositionHolder()) != Extractor.RESULT_END_OF_INPUT) {
            // Drain what is left.
        }

        val samples = output.track.samples
        assertEquals(1, samples.size)
        assertEquals(500_000L, samples.single().timeUs, "the block states its own time")
    }
}

@UnstableApi
class WavPackHeaderFieldsTest {

    @Test
    fun `WavPack 5 keeps the top bits of the sample counts in bytes 4 left spare`() {
        val header = block(blockIndex = 0x1_0000_0002L, totalSamples = 0x2_0000_0003L)

        assertEquals(0x1_0000_0002L, wavPackBlockIndex(header))
        assertEquals(0x2_0000_0003L, wavPackTotalSamples(header))
    }

    @Test
    fun `an unknown length reads as unknown rather than as four billion samples`() {
        assertEquals(-1L, wavPackTotalSamples(block(totalSamples = -1L)))
    }

    @Test
    fun `the flags name one of fifteen sample rates`() {
        assertEquals(44_100, wavPackSampleRate(9L shl 23))
        assertEquals(192_000, wavPackSampleRate(14L shl 23))
        assertEquals(0, wavPackSampleRate(15L shl 23))
    }
}
